@server = http://localhost:4004

### ------------------------------------------------------------------------
# Custom Function getItems
GET {{server}}/odata/v4/service/risk/getItems(quantity=100)
Content-Type: application/json

### ------------------------------------------------------------------------
# Custom Action createItem
POST {{server}}/odata/v4/service/risk/createItem
Content-Type: application/json

{
    "title": "Very Big Elephant and Hippo",
    "descr": "Test being tested",
    "quantity": 99
}

### ------------------------------------------------------------------------
# Get metadata
GET {{server}}/odata/v4/service/risk/$metadata?sap-language=6N
Content-Type: application/json

### ------------------------------------------------------------------------
# Custom Function callLocalhost
GET {{server}}/odata/v4/service/risk/callLocalhost()
Content-Type: application/json